title: Peaceful Ghosts # your name (or website title) here
logo: "/images/73177407_1132992833575742_8774958092434167311_n.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
These four Peaceful Ghosts are part of an initial edition of 10 hand-made NFTs aimed at bringing spiritual wellness initiatives into the blockchain ecosystem. Peaceful Ghosts are friendly ghosts, different from the specters that haunt most people: greed, anxiety, boredom, anger, fear. They are the source of ease and clarity and all the qualities that make life a joy to live. Normally they live out their days unnoticed in our minds, but now they are making an appearance on the Avalanche blockchain.
<br><br>
These first 10 NFTs are part of a proof-of-concept for a future programmatically generated NFT collection of Peaceful Ghosts that will be a part of a blockchain community building and spiritual wellness initiative. This project is supporting the United Nations SDG Agenda 2030 for good health and well-being.  
<br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
